### ISSUE TITLE
[Bug] `Could not check the JVM name!: java.lang.UnsupportedOperationException: Does not support method isInstanceOf`

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#243]
### Current Behavior

Occasionally, JMX connection attempts fail with a strange `UnsupportedOperationException`. Retrying this same request succeeds.

### Steps To Reproduce

1. `helm install cryostat --set storage.image.repository=quay.io/andrewazores/cryostat-storage --set storage.image.tag=seaweed-2 --set pvc.enabled=true ./charts/cryostat`
2. `oc expose svc cryostat --port 8181`
3. Open web UI, define `localhost:0` custom target
4. Start a recording on custom target
5. Try archiving recording

### Environment

```Markdown
Cryostat 3.0, running in OpenShift (crc) via helm chart: https://github.com/cryostatio/cryostat-helm/pull/111
```

### Anything else?

```
2024-01-17 19:29:52,308 INFO  [io.cry.tar.TargetConnectionManager] (executor-thread-10) Opening connection to service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi
2024-01-17 19:29:52,309 INFO  [io.cry.tar.TargetConnectionManager] (executor-thread-13) Removing cached connection for service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi: EXPIRED
2024-01-17 19:29:52,315 INFO  [io.cry.tar.TargetConnectionManager] (executor-thread-13) Removing cached connection for service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi: EXPLICIT
2024-01-17 19:29:52,321 INFO  [org.ope.jmc.rjmx] (executor-thread-1) Could not check the JVM name!: java.lang.UnsupportedOperationException: Does not support method isInstanceOf
	at org.openjdk.jmc.rjmx.services.internal.ServiceFactoryManager$UnsupportedInvocationHandler.invoke(ServiceFactoryManager.java:78)
	at jdk.proxy2/jdk.proxy2.$Proxy107.isInstanceOf(Unknown Source)
	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:652)
	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:612)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.getRuntimeBean(ConnectionToolkit.java:138)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.getVMName(ConnectionToolkit.java:424)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.isHotSpot(ConnectionToolkit.java:364)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.isDynamicFlightRecorderSupported(FlightRecorderServiceV2.java:113)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.<init>(FlightRecorderServiceV2.java:135)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceFactory.getServiceInstance(FlightRecorderServiceFactory.java:47)
	at io.cryostat.core.net.JmxFlightRecorderService.tryConnect(JmxFlightRecorderService.java:64)
	at io.cryostat.core.net.JmxFlightRecorderService.getAvailableRecordings(JmxFlightRecorderService.java:79)
	at io.cryostat.recordings.RecordingHelper.getDescriptorByName(RecordingHelper.java:387)
	at io.cryostat.recordings.Recordings.lambda$patchV1$15(Recordings.java:495)
	at io.cryostat.targets.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:202)
	at io.cryostat.targets.TargetConnectionManager_ClientProxy.executeConnectedTask(Unknown Source)
	at io.cryostat.recordings.Recordings.patchV1(Recordings.java:494)
	at io.cryostat.recordings.Recordings_Subclass.patchV1$$superforward(Unknown Source)
	at io.cryostat.recordings.Recordings_Subclass$$function$$7.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.cryostat.recordings.Recordings_Subclass.patchV1(Unknown Source)
	at io.cryostat.recordings.Recordings$quarkusrestinvoker$patchV1_6b47ee2f1948b117a8a36f0264bfaafcd42edc14.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-01-17 19:29:52,322 INFO  [org.ope.jmc.rjmx] (executor-thread-1) Could not check the JVM name!: java.lang.UnsupportedOperationException: Does not support method isInstanceOf
	at org.openjdk.jmc.rjmx.services.internal.ServiceFactoryManager$UnsupportedInvocationHandler.invoke(ServiceFactoryManager.java:78)
	at jdk.proxy2/jdk.proxy2.$Proxy107.isInstanceOf(Unknown Source)
	at java.management/java.lang.management.ManagementFactory.isInstanceOf(ManagementFactory.java:652)
	at java.management/java.lang.management.ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.java:612)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.getRuntimeBean(ConnectionToolkit.java:138)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.getVMName(ConnectionToolkit.java:424)
	at org.openjdk.jmc.rjmx.ConnectionToolkit.isSubstrateVm(ConnectionToolkit.java:369)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.isFlightRecorderDisabled(FlightRecorderServiceV2.java:118)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceV2.<init>(FlightRecorderServiceV2.java:135)
	at org.openjdk.jmc.rjmx.services.jfr.internal.FlightRecorderServiceFactory.getServiceInstance(FlightRecorderServiceFactory.java:47)
	at io.cryostat.core.net.JmxFlightRecorderService.tryConnect(JmxFlightRecorderService.java:64)
	at io.cryostat.core.net.JmxFlightRecorderService.getAvailableRecordings(JmxFlightRecorderService.java:79)
	at io.cryostat.recordings.RecordingHelper.getDescriptorByName(RecordingHelper.java:387)
	at io.cryostat.recordings.Recordings.lambda$patchV1$15(Recordings.java:495)
	at io.cryostat.targets.TargetConnectionManager.executeConnectedTask(TargetConnectionManager.java:202)
	at io.cryostat.targets.TargetConnectionManager_ClientProxy.executeConnectedTask(Unknown Source)
	at io.cryostat.recordings.Recordings.patchV1(Recordings.java:494)
	at io.cryostat.recordings.Recordings_Subclass.patchV1$$superforward(Unknown Source)
	at io.cryostat.recordings.Recordings_Subclass$$function$$7.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at io.cryostat.recordings.Recordings_Subclass.patchV1(Unknown Source)
	at io.cryostat.recordings.Recordings$quarkusrestinvoker$patchV1_6b47ee2f1948b117a8a36f0264bfaafcd42edc14.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-01-17 19:29:52,325 INFO  [io.qua.htt.access-log] (executor-thread-1) 192.168.130.1 - - [17/Jan/2024:19:29:52 +0000] "PATCH /api/v1/targets/service%3Ajmx%3Armi%3A%2F%2F%2Fjndi%2Frmi%3A%2F%2Flocalhost%3A0%2Fjmxrmi/recordings/test HTTP/1.1" 500 -
```

**Comment by andrewazores** [comment]
I haven't noticed this in quite a long time. Not sure what could have fixed it, but will close for now unless it comes up again.
