### ISSUE TITLE
[Bug] Topology view actions sometimes silently partially fail

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat3#389]
### Current Behavior

The various Topology view group-level actions sometimes silently fail in the background for a subset of the targets within the group. For example, 2/3 targets may actually have the default recording started upon them on the first attempt. Retrying the action is likely to start the recording on the one missed target as well. Similar for archiving, stopping, or deleting the group recordings.

### Expected Behavior

The requests should much more reliably execute against all targets in the group. If any failures occur there should be notifications.

### Environment

```Markdown
`./smoktest.bash -t`
```

**Comment by andrewazores** [comment]
I hit this with #342 checked out so the stack trace looks a little different, but I think it's likely to be the root cause here:

```
cryostat_1            | ERROR: Failure to synchronize existing target recording state for service:jmx:rmi:///jndi/rmi://localhost:0/jmxrmi
cryostat_1            | jakarta.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.
cryostat_1            | 	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:143)
cryostat_1            | 	at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:275)
cryostat_1            | 	at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.persist(Unknown Source)
cryostat_1            | 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:101)
cryostat_1            | 	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:96)
cryostat_1            | 	at io.quarkus.hibernate.orm.panache.PanacheEntityBase.persist(PanacheEntityBase.java:53)
cryostat_1            | 	at io.cryostat.recordings.RecordingHelper.listActiveRecordings(RecordingHelper.java:285)
cryostat_1            | 	at io.cryostat.recordings.RecordingHelper_ClientProxy.listActiveRecordings(Unknown Source)
cryostat_1            | 	at io.cryostat.graphql.TargetNodes.recordings(TargetNodes.java:111)
cryostat_1            | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cryostat_1            | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
cryostat_1            | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cryostat_1            | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
cryostat_1            | 	at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:97)
cryostat_1            | 	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:83)
cryostat_1            | 	at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
cryostat_1            | 	at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.BlockingHelper.lambda$runBlocking$0(BlockingHelper.java:30)
cryostat_1            | 	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
cryostat_1            | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
cryostat_1            | 	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
cryostat_1            | 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
cryostat_1            | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
cryostat_1            | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
cryostat_1            | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
cryostat_1            | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
cryostat_1            | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
cryostat_1            | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
cryostat_1            | 	at java.base/java.lang.Thread.run(Thread.java:840)
```

This is also similar to another failure we have seen where the GraphQL-powered "All Targets" archive view occasionally fails, but can usually succeed on the next retry.
